version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: eventos_ias
      MYSQL_USER:  juan-ias
      MYSQL_PASSWORD: 123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "8081:8081"

volumes:
  db_data: